### ISSUE TITLE
Godot sharp support

### ISSUE THREAD

**Issue by tapir** [GodotExplorer/godot-tools#46]
Is it possible to get C# support for the upcoming 3.0 release

**Comment by mfdeveloper** [comment]
Hey @tapir , you don't need of C# support from this plugin. You can use any C# editor (Visual Studio Community Edition, Monodevelop, Xamarin Studio, VSCode with others plugins...) because the Godot 3.0 engine creates a .net solution with the `.dll` reference with the needed libraries for autocomplete.

See this video: https://www.youtube.com/watch?v=xQMBCTvVoa8

**Comment by Geequlim** [comment]
No plan to support C#.
You may try other C#/mono related plugins.
